version: "3"

services:
    app:
        build: .
        ports:
            - 9021:3000 # default: 9021:3000
        depends_on:
            - db
    db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        env_file:
            - .env.db
        volumes:
            - db_volume:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
    db_volume:
